from PyQt5 import QtCore, QtWidgets


class Ui_ExportOptDlg(object):
    def setupUi(self, ExportOptDlg):
        ExportOptDlg.setObjectName("ExportOptDlg")
        ExportOptDlg.resize(380, 380)
        ExportOptDlg.setMinimumSize(QtCore.QSize(380, 380))
        self.verticalLayout = QtWidgets.QVBoxLayout(ExportOptDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(2, -1, 2, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_seqStart = QtWidgets.QLabel(ExportOptDlg)
        self.label_seqStart.setObjectName("label_seqStart")
        self.gridLayout.addWidget(self.label_seqStart, 7, 0, 1, 1)
        self.labelForce = QtWidgets.QLabel(ExportOptDlg)
        self.labelForce.setObjectName("labelForce")
        self.gridLayout.addWidget(self.labelForce, 1, 0, 1, 1)
        self.startLineEdit = QtWidgets.QLineEdit(ExportOptDlg)
        self.startLineEdit.setEnabled(True)
        self.startLineEdit.setObjectName("startLineEdit")
        self.gridLayout.addWidget(self.startLineEdit, 3, 1, 1, 1)
        self.safLineCmbBox = QtWidgets.QComboBox(ExportOptDlg)
        self.safLineCmbBox.setObjectName("safLineCmbBox")
        self.safLineCmbBox.addItem("")
        self.safLineCmbBox.addItem("")
        self.gridLayout.addWidget(self.safLineCmbBox, 5, 1, 1, 1)
        self.label_Lang = QtWidgets.QLabel(ExportOptDlg)
        self.label_Lang.setObjectName("label_Lang")
        self.gridLayout.addWidget(self.label_Lang, 0, 0, 1, 1)
        self.delimCmbBox = QtWidgets.QComboBox(ExportOptDlg)
        self.delimCmbBox.setObjectName("delimCmbBox")
        self.delimCmbBox.addItem("")
        self.delimCmbBox.addItem("")
        self.gridLayout.addWidget(self.delimCmbBox, 9, 1, 1, 1)
        self.langCmbBox = QtWidgets.QComboBox(ExportOptDlg)
        self.langCmbBox.setObjectName("langCmbBox")
        self.langCmbBox.addItem("")
        self.langCmbBox.addItem("")
        self.langCmbBox.addItem("")
        self.langCmbBox.addItem("")
        self.langCmbBox.addItem("")
        self.gridLayout.addWidget(self.langCmbBox, 0, 1, 1, 1)
        self.label_seqInterval = QtWidgets.QLabel(ExportOptDlg)
        self.label_seqInterval.setObjectName("label_seqInterval")
        self.gridLayout.addWidget(self.label_seqInterval, 8, 0, 1, 1)
        self.seqStartSpinBox = QtWidgets.QSpinBox(ExportOptDlg)
        self.seqStartSpinBox.setMinimum(1)
        self.seqStartSpinBox.setMaximum(99999)
        self.seqStartSpinBox.setObjectName("seqStartSpinBox")
        self.gridLayout.addWidget(self.seqStartSpinBox, 7, 1, 1, 1)
        self.label_Incr = QtWidgets.QLabel(ExportOptDlg)
        self.label_Incr.setObjectName("label_Incr")
        self.gridLayout.addWidget(self.label_Incr, 2, 0, 1, 1)
        self.label_StartText = QtWidgets.QLabel(ExportOptDlg)
        self.label_StartText.setObjectName("label_StartText")
        self.gridLayout.addWidget(self.label_StartText, 3, 0, 1, 1)
        self.label_Delim = QtWidgets.QLabel(ExportOptDlg)
        self.label_Delim.setObjectName("label_Delim")
        self.gridLayout.addWidget(self.label_Delim, 9, 0, 1, 1)
        self.seqNumCmbBox = QtWidgets.QComboBox(ExportOptDlg)
        self.seqNumCmbBox.setObjectName("seqNumCmbBox")
        self.seqNumCmbBox.addItem("")
        self.seqNumCmbBox.addItem("")
        self.gridLayout.addWidget(self.seqNumCmbBox, 6, 1, 1, 1)
        self.incrCmbBox = QtWidgets.QComboBox(ExportOptDlg)
        self.incrCmbBox.setObjectName("incrCmbBox")
        self.incrCmbBox.addItem("")
        self.incrCmbBox.addItem("")
        self.gridLayout.addWidget(self.incrCmbBox, 2, 1, 1, 1)
        self.seqIntervalSpinBox = QtWidgets.QSpinBox(ExportOptDlg)
        self.seqIntervalSpinBox.setMinimum(1)
        self.seqIntervalSpinBox.setMaximum(99999)
        self.seqIntervalSpinBox.setObjectName("seqIntervalSpinBox")
        self.gridLayout.addWidget(self.seqIntervalSpinBox, 8, 1, 1, 1)
        self.forceCmbBox = QtWidgets.QComboBox(ExportOptDlg)
        self.forceCmbBox.setObjectName("forceCmbBox")
        self.forceCmbBox.addItem("")
        self.forceCmbBox.addItem("")
        self.gridLayout.addWidget(self.forceCmbBox, 1, 1, 1, 1)
        self.label_SafLine = QtWidgets.QLabel(ExportOptDlg)
        self.label_SafLine.setObjectName("label_SafLine")
        self.gridLayout.addWidget(self.label_SafLine, 5, 0, 1, 1)
        self.label_SeqNum = QtWidgets.QLabel(ExportOptDlg)
        self.label_SeqNum.setObjectName("label_SeqNum")
        self.gridLayout.addWidget(self.label_SeqNum, 6, 0, 1, 1)
        self.label_EndText = QtWidgets.QLabel(ExportOptDlg)
        self.label_EndText.setObjectName("label_EndText")
        self.gridLayout.addWidget(self.label_EndText, 4, 0, 1, 1)
        self.endLineEdit = QtWidgets.QLineEdit(ExportOptDlg)
        self.endLineEdit.setObjectName("endLineEdit")
        self.gridLayout.addWidget(self.endLineEdit, 4, 1, 1, 1)
        self.leadingZeroCmbBox = QtWidgets.QComboBox(ExportOptDlg)
        self.leadingZeroCmbBox.setObjectName("leadingZeroCmbBox")
        self.leadingZeroCmbBox.addItem("")
        self.leadingZeroCmbBox.addItem("")
        self.gridLayout.addWidget(self.leadingZeroCmbBox, 10, 1, 1, 1)
        self.labelLeadingZero = QtWidgets.QLabel(ExportOptDlg)
        self.labelLeadingZero.setObjectName("labelLeadingZero")
        self.gridLayout.addWidget(self.labelLeadingZero, 10, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(ExportOptDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ExportOptDlg)
        self.buttonBox.accepted.connect(ExportOptDlg.accept) # type: ignore
        self.buttonBox.rejected.connect(ExportOptDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExportOptDlg)
        ExportOptDlg.setTabOrder(self.langCmbBox, self.forceCmbBox)
        ExportOptDlg.setTabOrder(self.forceCmbBox, self.incrCmbBox)
        ExportOptDlg.setTabOrder(self.incrCmbBox, self.startLineEdit)
        ExportOptDlg.setTabOrder(self.startLineEdit, self.endLineEdit)
        ExportOptDlg.setTabOrder(self.endLineEdit, self.safLineCmbBox)
        ExportOptDlg.setTabOrder(self.safLineCmbBox, self.seqNumCmbBox)
        ExportOptDlg.setTabOrder(self.seqNumCmbBox, self.seqStartSpinBox)
        ExportOptDlg.setTabOrder(self.seqStartSpinBox, self.seqIntervalSpinBox)

    def retranslateUi(self, ExportOptDlg):
        _translate = QtCore.QCoreApplication.translate
        ExportOptDlg.setWindowTitle(_translate("ExportOptDlg", "Export Options"))
        self.label_seqStart.setText(_translate("ExportOptDlg", "Seq. Num. Start"))
        self.labelForce.setText(_translate("ExportOptDlg", "Address Force Output "))
        self.safLineCmbBox.setItemText(0, _translate("ExportOptDlg", "No"))
        self.safLineCmbBox.setItemText(1, _translate("ExportOptDlg", "Yes"))
        self.label_Lang.setText(_translate("ExportOptDlg", "G-code"))
        self.delimCmbBox.setItemText(0, _translate("ExportOptDlg", "No"))
        self.delimCmbBox.setItemText(1, _translate("ExportOptDlg", "Yes"))
        self.langCmbBox.setItemText(0, _translate("ExportOptDlg", "ISO IJ ARC INCR"))
        self.langCmbBox.setItemText(1, _translate("ExportOptDlg", "ISO IJ ARC ABS"))
        self.langCmbBox.setItemText(2, _translate("ExportOptDlg", "ISO R ARC"))
        self.langCmbBox.setItemText(3, _translate("ExportOptDlg", "ISO NO ARC"))
        self.langCmbBox.setItemText(4, _translate("ExportOptDlg", "PLOT DATA"))
        self.label_seqInterval.setText(_translate("ExportOptDlg", "Seq. Num. Interval"))
        self.label_Incr.setText(_translate("ExportOptDlg", "Incremental Mode"))
        self.label_StartText.setText(_translate("ExportOptDlg", "Start Program Text"))
        self.label_Delim.setText(_translate("ExportOptDlg", "Delimeter"))
        self.seqNumCmbBox.setItemText(0, _translate("ExportOptDlg", "No"))
        self.seqNumCmbBox.setItemText(1, _translate("ExportOptDlg", "Yes"))
        self.incrCmbBox.setItemText(0, _translate("ExportOptDlg", "No"))
        self.incrCmbBox.setItemText(1, _translate("ExportOptDlg", "Yes"))
        self.forceCmbBox.setItemText(0, _translate("ExportOptDlg", "No"))
        self.forceCmbBox.setItemText(1, _translate("ExportOptDlg", "Yes"))
        self.label_SafLine.setText(_translate("ExportOptDlg", "Safety Line"))
        self.label_SeqNum.setText(_translate("ExportOptDlg", "Seq. Num."))
        self.label_EndText.setText(_translate("ExportOptDlg", "End Program Text"))
        self.leadingZeroCmbBox.setItemText(0, _translate("ExportOptDlg", "No"))
        self.leadingZeroCmbBox.setItemText(1, _translate("ExportOptDlg", "Yes"))
        self.labelLeadingZero.setText(_translate("ExportOptDlg", "Leading Zero (G,M,T,H,D)"))
