from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qsci import QsciScintilla
from pyqtgraph.opengl import GLViewWidget

class Editor(QsciScintilla):
    def __init__(self, parent=None):
        super().__init__(parent)
        
        self.setAcceptDrops(False)

class PlotView(GLViewWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

    def mouseMoveEvent(self, ev):
        lpos = ev.position() if hasattr(ev, 'position') else ev.localPos()
        if not hasattr(self, 'mousePos'):
            self.mousePos = lpos
        diff = lpos - self.mousePos
        self.mousePos = lpos
        if ev.buttons() == QtCore.Qt.MouseButton.LeftButton:
            if (ev.modifiers() & QtCore.Qt.KeyboardModifier.ControlModifier):
                self.pan(diff.x(), diff.y(), 0, relative='view')
            else:
                if self.opts["rotationMethod"] == "euler":
                    self.orbit(-diff.x(), diff.y())
                else:
                    self.pan(diff.x(), diff.y(), 0, relative='view')
        elif ev.buttons() == QtCore.Qt.MouseButton.MiddleButton:
            if (ev.modifiers() & QtCore.Qt.KeyboardModifier.ControlModifier):
                self.pan(diff.x(), diff.y(), 0, relative='view')
            else:
                if self.opts["rotationMethod"] == "euler":
                    self.orbit(-diff.x(), diff.y())
                else:
                    self.pan(diff.x(), diff.y(), 0, relative='view')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 650)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        self.editor = Editor(self.splitter)

        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelX = QtWidgets.QLabel(self.layoutWidget)
        self.labelX.setObjectName("labelX")
        self.horizontalLayout_2.addWidget(self.labelX)
        self.lineEditX = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditX.setReadOnly(True)
        self.lineEditX.setObjectName("lineEditX")
        self.horizontalLayout_2.addWidget(self.lineEditX)
        self.labelY = QtWidgets.QLabel(self.layoutWidget)
        self.labelY.setObjectName("labelY")
        self.horizontalLayout_2.addWidget(self.labelY)
        self.lineEditY = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditY.setReadOnly(True)
        self.lineEditY.setObjectName("lineEditY")
        self.horizontalLayout_2.addWidget(self.lineEditY)
        self.labelZ = QtWidgets.QLabel(self.layoutWidget)
        self.labelZ.setObjectName("labelZ")
        self.horizontalLayout_2.addWidget(self.labelZ)
        self.lineEditZ = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditZ.setReadOnly(True)
        self.lineEditZ.setObjectName("lineEditZ")
        self.horizontalLayout_2.addWidget(self.lineEditZ)
        self.label_I = QtWidgets.QLabel(self.layoutWidget)
        self.label_I.setObjectName("label_I")
        self.horizontalLayout_2.addWidget(self.label_I)
        self.lineEdit_I = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_I.setReadOnly(True)
        self.lineEdit_I.setObjectName("lineEdit_I")
        self.horizontalLayout_2.addWidget(self.lineEdit_I)
        self.label_J = QtWidgets.QLabel(self.layoutWidget)
        self.label_J.setObjectName("label_J")
        self.horizontalLayout_2.addWidget(self.label_J)
        self.lineEdit_J = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_J.setReadOnly(True)
        self.lineEdit_J.setObjectName("lineEdit_J")
        self.horizontalLayout_2.addWidget(self.lineEdit_J)
        self.label_K = QtWidgets.QLabel(self.layoutWidget)
        self.label_K.setObjectName("label_K")
        self.horizontalLayout_2.addWidget(self.label_K)
        self.lineEdit_K = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_K.setReadOnly(True)
        self.lineEdit_K.setObjectName("lineEdit_K")
        self.horizontalLayout_2.addWidget(self.lineEdit_K)
        self.labelFeed = QtWidgets.QLabel(self.layoutWidget)
        self.labelFeed.setObjectName("labelFeed")
        self.horizontalLayout_2.addWidget(self.labelFeed)
        self.lineEditFeed = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditFeed.setReadOnly(True)
        self.lineEditFeed.setObjectName("lineEditFeed")
        self.horizontalLayout_2.addWidget(self.lineEditFeed)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.graphicsView = PlotView()

        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuArc_Type = QtWidgets.QMenu(self.menuSettings)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/icons/arc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuArc_Type.setIcon(icon)
        self.menuArc_Type.setObjectName("menuArc_Type")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menuCNC_Functions = QtWidgets.QMenu(self.menubar)
        self.menuCNC_Functions.setObjectName("menuCNC_Functions")
        self.menuBlockNumbers = QtWidgets.QMenu(self.menuCNC_Functions)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resource/icons/number.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBlockNumbers.setIcon(icon1)
        self.menuBlockNumbers.setObjectName("menuBlockNumbers")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setObjectName("toolBar")
        self.toolBar1 = QtWidgets.QToolBar(MainWindow)
        self.toolBar1.setIconSize(QtCore.QSize(30, 30))
        self.toolBar1.setObjectName("toolBar1")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar1)

        self.actionNew = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resource/icons/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon2)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resource/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon3)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resource/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resource/icons/save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon5)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resource/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/resource/icons/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon7)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/resource/icons/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon8)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/resource/icons/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon9)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/resource/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon10)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/resource/icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon11)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSelectAll = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/resource/icons/select-all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectAll.setIcon(icon12)
        self.actionSelectAll.setObjectName("actionSelectAll")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/resource/icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon13)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFindReplace = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/resource/icons/find-replace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFindReplace.setIcon(icon14)
        self.actionFindReplace.setObjectName("actionFindReplace")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/resource/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon15)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        self.actionPlay.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/resource/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon16)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setCheckable(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/resource/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon17)
        self.actionStop.setObjectName("actionStop")
        self.actionExportData = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/resource/icons/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportData.setIcon(icon18)
        self.actionExportData.setObjectName("actionExportData")
        self.action3D = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/resource/icons/3D.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3D.setIcon(icon19)
        self.action3D.setObjectName("action3D")
        self.actionTop = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/resource/icons/top.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTop.setIcon(icon20)
        self.actionTop.setObjectName("actionTop")
        self.actionFront = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/resource/icons/front.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFront.setIcon(icon21)
        self.actionFront.setObjectName("actionFront")
        self.actionLeft = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/resource/icons/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLeft.setIcon(icon22)
        self.actionLeft.setObjectName("actionLeft")
        self.actionRelative_to_start = QtWidgets.QAction(MainWindow)
        self.actionRelative_to_start.setCheckable(True)
        self.actionRelative_to_start.setObjectName("actionRelative_to_start")
        self.actionAbsolute = QtWidgets.QAction(MainWindow)
        self.actionAbsolute.setCheckable(True)
        self.actionAbsolute.setObjectName("actionAbsolute")
        self.actionRadius_value = QtWidgets.QAction(MainWindow)
        self.actionRadius_value.setCheckable(True)
        self.actionRadius_value.setObjectName("actionRadius_value")

        self.actionGroupArcType = QtWidgets.QActionGroup(MainWindow)
        relativeStart = self.actionGroupArcType.addAction(self.actionRelative_to_start)
        absolute = self.actionGroupArcType.addAction(self.actionAbsolute)
        radius = self.actionGroupArcType.addAction(self.actionRadius_value)

        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/resource/icons/zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_In.setIcon(icon23)
        self.actionZoom_In.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/resource/icons/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Out.setIcon(icon24)
        self.actionZoom_Out.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionStep_Backward = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/resource/icons/step_backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStep_Backward.setIcon(icon25)
        self.actionStep_Backward.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionStep_Backward.setObjectName("actionStep_Backward")
        self.actionStep_Forward = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/resource/icons/step_forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStep_Forward.setIcon(icon26)
        self.actionStep_Forward.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionStep_Forward.setObjectName("actionStep_Forward")
        self.actionLatheMode = QtWidgets.QAction(MainWindow)
        self.actionLatheMode.setCheckable(True)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/resource/icons/lathe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLatheMode.setIcon(icon27)
        self.actionLatheMode.setObjectName("actionLatheMode")
        self.actionGrid = QtWidgets.QAction(MainWindow)
        self.actionGrid.setCheckable(True)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/resource/icons/grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGrid.setIcon(icon28)
        self.actionGrid.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionGrid.setObjectName("actionGrid")
        self.actionStatistics = QtWidgets.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/resource/icons/stat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStatistics.setIcon(icon29)
        self.actionStatistics.setObjectName("actionStatistics")
        self.actionRenumber = QtWidgets.QAction(MainWindow)
        self.actionRenumber.setObjectName("actionRenumber")
        self.actionNumbRemove = QtWidgets.QAction(MainWindow)
        self.actionNumbRemove.setObjectName("actionNumbRemove")
        self.actionRemoveEmptyLines = QtWidgets.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/resource/icons/removeSpaces.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemoveEmptyLines.setIcon(icon30)
        self.actionRemoveEmptyLines.setObjectName("actionRemoveEmptyLines")
        self.actionRemoveSpaces = QtWidgets.QAction(MainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/resource/icons/removeEmptyLines.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemoveSpaces.setIcon(icon31)
        self.actionRemoveSpaces.setObjectName("actionRemoveSpaces")
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSaveAs)
        self.menu_File.addAction(self.actionExportData)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu_Edit.addAction(self.actionUndo)
        self.menu_Edit.addAction(self.actionRedo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionCut)
        self.menu_Edit.addAction(self.actionCopy)
        self.menu_Edit.addAction(self.actionPaste)
        self.menu_Edit.addAction(self.actionSelectAll)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionFindReplace)
        self.menu_Help.addAction(self.actionAbout)

        self.menuArc_Type.addAction(relativeStart)
        self.menuArc_Type.addAction(absolute)
        self.menuArc_Type.addAction(radius)

        self.menuSettings.addAction(self.menuArc_Type.menuAction())
        self.menuSettings.addAction(self.actionLatheMode)
        self.menu_View.addAction(self.actionRefresh)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.actionZoom_In)
        self.menu_View.addAction(self.actionZoom_Out)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.action3D)
        self.menu_View.addAction(self.actionTop)
        self.menu_View.addAction(self.actionFront)
        self.menu_View.addAction(self.actionLeft)
        self.menu_View.addAction(self.actionGrid)
        self.menuBlockNumbers.addSeparator()
        self.menuBlockNumbers.addAction(self.actionRenumber)
        self.menuBlockNumbers.addAction(self.actionNumbRemove)
        self.menuCNC_Functions.addAction(self.menuBlockNumbers.menuAction())
        self.menuCNC_Functions.addAction(self.actionRemoveSpaces)
        self.menuCNC_Functions.addAction(self.actionRemoveEmptyLines)
        self.menuCNC_Functions.addAction(self.actionStatistics)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menuCNC_Functions.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSaveAs)
        self.toolBar.addAction(self.actionExportData)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addAction(self.actionSelectAll)
        self.toolBar.addAction(self.actionFindReplace)

        self.langCombo = QtWidgets.QComboBox(MainWindow)
        self.langCombo.addItem("Text File")
        self.langCombo.addItem("ISO G-Code")
        self.langCombo.setToolTip("File Type")
        self.toolBar1.addWidget(self.langCombo)
        self.toolBar1.addSeparator()
        self.toolBar1.addAction(self.actionRefresh)
        self.toolBar1.addAction(self.actionZoom_In)
        self.toolBar1.addAction(self.actionZoom_Out)
        self.toolBar1.addAction(self.action3D)
        self.toolBar1.addAction(self.actionTop)
        self.toolBar1.addAction(self.actionFront)
        self.toolBar1.addAction(self.actionLeft)
        self.toolBar1.addAction(self.actionGrid)
        self.toolBar1.addSeparator()
        self.toolBar1.addAction(self.actionStep_Backward)
        self.toolBar1.addAction(self.actionPlay)
        self.toolBar1.addAction(self.actionStop)
        self.toolBar1.addAction(self.actionStep_Forward)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Easy G-code Plot"))
        self.labelX.setText(_translate("MainWindow", "X:"))
        self.labelY.setText(_translate("MainWindow", "Y:"))
        self.labelZ.setText(_translate("MainWindow", "Z:"))
        self.label_I.setText(_translate("MainWindow", "I:"))
        self.label_J.setText(_translate("MainWindow", "J:"))
        self.label_K.setText(_translate("MainWindow", "K:"))
        self.labelFeed.setText(_translate("MainWindow", "F:"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuArc_Type.setTitle(_translate("MainWindow", "Arc Type"))
        self.menu_View.setTitle(_translate("MainWindow", "&View"))
        self.menuCNC_Functions.setTitle(_translate("MainWindow", "CNC Functions"))
        self.menuBlockNumbers.setTitle(_translate("MainWindow", "Block Numbers"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save &As"))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Alt+X"))
        self.actionUndo.setText(_translate("MainWindow", "&Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "&Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionCut.setText(_translate("MainWindow", "Cu&t"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "&Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "&Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSelectAll.setText(_translate("MainWindow", "Select &All"))
        self.actionSelectAll.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionFindReplace.setText(_translate("MainWindow", "&Find and Replace"))
        self.actionFindReplace.setToolTip(_translate("MainWindow", "Find and Replace"))
        self.actionFindReplace.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionRefresh.setToolTip(_translate("MainWindow", "Refresh"))
        self.actionPlay.setText(_translate("MainWindow", "Play"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionExportData.setText(_translate("MainWindow", "Export &Data"))
        self.action3D.setText(_translate("MainWindow", "View 3D"))
        self.action3D.setToolTip(_translate("MainWindow", "View 3D"))
        self.actionTop.setText(_translate("MainWindow", "View Top"))
        self.actionTop.setToolTip(_translate("MainWindow", "View Top (XY/G17)"))
        self.actionFront.setText(_translate("MainWindow", "View Front"))
        self.actionFront.setToolTip(_translate("MainWindow", "View Front (XZ/G18)"))
        self.actionLeft.setText(_translate("MainWindow", "View Left"))
        self.actionLeft.setToolTip(_translate("MainWindow", "View Left (YZ/G19)"))
        self.actionRelative_to_start.setText(_translate("MainWindow", "Relative to start"))
        self.actionAbsolute.setText(_translate("MainWindow", "Absolute arc center"))
        self.actionRadius_value.setText(_translate("MainWindow", "Radius value"))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_In.setToolTip(_translate("MainWindow", "Zoom In"))
        self.actionZoom_In.setShortcut(_translate("MainWindow", "Ctrl++"))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoom_Out.setToolTip(_translate("MainWindow", "Zoom Out"))
        self.actionZoom_Out.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionStep_Backward.setText(_translate("MainWindow", "Step Backward"))
        self.actionStep_Backward.setToolTip(_translate("MainWindow", "Step Backward"))
        self.actionStep_Forward.setText(_translate("MainWindow", "Step Forward"))
        self.actionLatheMode.setText(_translate("MainWindow", "Lathe Mode"))
        self.actionLatheMode.setToolTip(_translate("MainWindow", "Lathe Mode"))
        self.actionGrid.setText(_translate("MainWindow", "Grid"))
        self.actionGrid.setToolTip(_translate("MainWindow", "Grid"))
        self.actionStatistics.setText(_translate("MainWindow", "Statistics"))
        self.actionRenumber.setText(_translate("MainWindow", "Renumber"))
        self.actionNumbRemove.setText(_translate("MainWindow", "Remove"))
        self.actionRemoveEmptyLines.setText(_translate("MainWindow", "Remove Empty Lines"))
        self.actionRemoveSpaces.setText(_translate("MainWindow", "Remove Spaces"))